# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('sed', 'Sedan'), ('hat', 'Hatchback'), ('est', 'Estate'), ('mpv', 'MPV'), ('cop', 'Coupe'), ('con', 'Convertible'), ('suv', 'SUV'), ('pic', 'Pickup'), ('cab', 'Cabriolet'), ('com', 'Commercial'), ('van', 'Van'), ('oth', 'Other')], default='sal', help_text='Choose car body type', max_length=3, verbose_name='Body')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_doors', models.DecimalField(decimal_places=0, default=4, max_digits=1, verbose_name='Doors')),
                ('passangers', models.DecimalField(decimal_places=0, default=5, max_digits=1)),
                ('car_image', models.ImageField(upload_to='images')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.BodyType')),
            ],
            options={
                'ordering': ['car_make_and_model__manufacturer_name_and_logo__manufacturer_logo_name', 'car_make_and_model__manufacturer_model_name'],
            },
        ),
        migrations.CreateModel(
            name='CarEngineSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_size', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='CarFuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('d', 'Disel'), ('p', 'Petrol'), ('h', 'Hybrid'), ('e', 'Electric')], default='p', help_text='Choose Fuel Type', max_length=1, verbose_name='Fuel Type')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_status', models.CharField(choices=[('a', 'Available'), ('n', 'Not Available'), ('m', 'Maintenance'), ('r', 'Reserved')], default='a', help_text='Car availability', max_length=1, verbose_name='Status')),
                ('date_of_return', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.Car')),
            ],
            options={
                'ordering': ['car__car_make_and_model__manufacturer_name_and_logo__manufacturer_logo_name', 'car__car_make_and_model__manufacturer_model_name', '-engine_size', 'car_status'],
            },
        ),
        migrations.CreateModel(
            name='CarManufacturerAndLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_logo', models.ImageField(upload_to='images', verbose_name='Car Logo')),
                ('manufacturer_logo_name', models.CharField(help_text='Enter a car manufacturer name e.g. Ford', max_length=15, verbose_name='Make')),
            ],
            options={
                'verbose_name_plural': 'Car Make and Logo',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_model_name', models.CharField(help_text='Enter a car manufacturer model name e.g. Mustang', max_length=15, verbose_name='Model')),
                ('manufacturer_name_and_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarManufacturerAndLogo', verbose_name='Car Make and Logo')),
            ],
            options={
                'ordering': ['manufacturer_name_and_logo', 'manufacturer_model_name'],
            },
        ),
        migrations.CreateModel(
            name='CarRegistrationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(help_text='Car Registration Number', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(help_text='Enter a car specs (e.g. Audio System, Sunroof, Airbags)', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CarTransmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('m', 'Manual'), ('a', 'Automatic'), ('s', 'Semi-automatic')], default='m', help_text='Choose transmission type', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.PositiveIntegerField(choices=[(1, 'Mini'), (2, 'Economy'), (3, 'Compact'), (4, 'Intermediate'), (5, 'Carrier'), (6, 'Premium'), (7, 'Sport'), (8, 'Other')], default=3, help_text='Choose car type')),
            ],
            options={
                'ordering': ['car_type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartype',
            unique_together=set([('car_type',)]),
        ),
        migrations.AlterUniqueTogether(
            name='cartransmissiontype',
            unique_together=set([('transmission',)]),
        ),
        migrations.AlterUniqueTogether(
            name='carspecs',
            unique_together=set([('specification',)]),
        ),
        migrations.AlterUniqueTogether(
            name='carmanufacturerandlogo',
            unique_together=set([('manufacturer_logo_name',)]),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='car_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarRegistrationNumber'),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='car_specifications',
            field=models.ManyToManyField(to='cars_fleet.CarSpecs', verbose_name='Specs'),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='engine_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarEngineSize'),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarFuelType'),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='rented_to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarTransmissionType'),
        ),
        migrations.AlterUniqueTogether(
            name='carfueltype',
            unique_together=set([('fuel',)]),
        ),
        migrations.AlterUniqueTogether(
            name='carenginesize',
            unique_together=set([('engine_size',)]),
        ),
        migrations.AddField(
            model_name='car',
            name='car_make_and_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarModel', verbose_name='Make and Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_fleet.CarType'),
        ),
        migrations.AlterUniqueTogether(
            name='bodytype',
            unique_together=set([('body_type',)]),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('manufacturer_name_and_logo', 'manufacturer_model_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set([('car_make_and_model', 'car_body', 'car_type', 'num_of_doors', 'passangers')]),
        ),
    ]
